# Site Settings
locale        : "en-US"
title         : "Sasha Zink Portfolio"
title_separator: "-"
name          : "Sasha Zink"
description   : "M.S. in Human Language Technology · NLP Portfolio"
url           : "https://sshzink.github.io"
baseurl       : ""
repository    : "sshzink/sshzink.github.io"

# Site Author
author:
  name        : "Sasha Zink"
  avatar      : "profile.jpg" # Add your profile pic to /images
  bio         : "I’m completing my M.S. in Human Language Technology at the University of Arizona, specializing in NLP."
  location    : "Austin, TX"
  email       : "zink.alec@gmail.com"
  github      : "sshzink"
  linkedin    : #"https://www.linkedin.com/"

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Output
permalink: /:categories/:title/
timezone: America/Chicago
